---
- name: Ensure Redis is present
  apt:
    pkg: redis-server
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure Redis is started
  ansible.builtin.systemd:
    name: redis-server
    state: started
    enabled: yes

- name: Ensure Redis parameters are configured
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "{{ item.line_to_match }}"
    line: "{{ item.line_to_configure }}"
  with_items:
    - { line_to_match: "maxmemory", line_to_configure: "maxmemory 512MB" }
    - { line_to_match: "bind", line_to_configure: "bind 0.0.0.0" }
    - { line_to_match: "maxmemory-policy", line_to_configure: "maxmemory-policy allkeys-lru" }
    - { line_to_match: "maxmemory-samples", line_to_configure: "maxmemory-samples 10" }
    - { line_to_match: "^# requirepass", line_to_configure: "requirepass {{ vault_redis_password | default('') }}" }
    - { line_to_match: "^requirepass", line_to_configure: "requirepass {{ vault_redis_password | default('') }}" }
    - { line_to_match: "protected-mode", line_to_configure: "protected-mode no" }
  register: redis_conf
  when: vault_redis_password is defined

- name: Ensure redis service is restarted
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
  when: redis_conf.changed
