repos:
- repo: local
  hooks:
    - id: terraform-hooks
      name: Terraform Hooks
      entry: bash -c 'cd terraform && pre-commit run --all-files'
      language: system
      files: ^terraform/
      pass_filenames: false