---
- block:
  - name: Checkout colosseum
    ansible.builtin.git:
      repo: 'https://github.com/h3nnn4n/colosseum'
      dest: /home/devops/colosseum
      version: develop  # FIXME: Should be a release branch

  - name: Ensure the workers are not running
    ansible.builtin.command: pkill -f tournament_online
    ignore_errors: yes
    become: true

  - name: Ensure poetry is available
    command: "/home/devops/pyenv/shims/python -m pip install poetry"
    ignore_errors: yes

  - name: Install project deps with Poetry
    shell: "/home/devops/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "/home/devops/colosseum"

  - name: Decrypt and copy secret file
    copy:
      src: dot_env
      dest: /home/devops/colosseum/.env
      decrypt: true
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Start workers
    shell: "/home/devops/pyenv/shims/python -m poetry run python tournament_online.py"
    args:
      chdir: "/home/devops/colosseum"

  become: true
  become_method: su
  become_user: devops
