---
- block:
  - name: Checkout colosseum
    ansible.builtin.git:
      repo: 'https://github.com/h3nnn4n/colosseum'
      dest: '{{ install_folder }}/colosseum'
      version: "{{ deploy_branch }}"

  - name: Ensure poetry is available
    command: "{{ install_folder }}/pyenv/shims/python3 -m pip install poetry"
    ignore_errors: yes

  - name: Install project deps with Poetry
    shell: "{{ install_folder }}/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "{{ install_folder }}/colosseum"

  - name: Setup dot env
    template:
      src: dot_env
      dest: "{{ install_folder }}/colosseum/.env"
      decrypt: true
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Stop all workers
    command: |
      pkill -f tournament_online
    ignore_errors: true

  - name: Clean log and old files
    shell: |
      find . -name '*.log' -delete
      find . -name '*.jsonl' -delete
    ignore_errors: true
    args:
      chdir: "{{ install_folder }}/colosseum"

  - name: Start workers
    shell: |
      for i in `seq {{ colosseum_worker_count | default(1) }}`;
      do
        while [[ true ]]; do {{ install_folder }}/pyenv/shims/python3 -m poetry run python3 tournament_online.py; done &
      done
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum"
    when: colosseum_worker_count | default(1) > 0

  become: true
  become_method: su
  become_user: devops
