repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      files: ^terraform/

    - id: end-of-file-fixer
      files: ^terraform/

    - id: check-yaml
      files: ^terraform/

    - id: check-added-large-files
      files: ^terraform/

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.85.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-diff
      files: ^terraform/

    - id: terraform_tflint
      args:
        - --args=--format=compact
      files: ^terraform/

    - id: terraform_validate
      args:
        - --args=-json
      files: ^terraform/
