---
- block:
  - name: Checkout colosseum
    git:
      repo: https://github.com/h3nnn4n/colosseum_website
      dest: "{{ install_folder }}/colosseum_website"
      version: "{{ deploy_branch }}"

  - name: Install project deps with Poetry
    shell: "{{ install_folder }}/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Setup .env file
    template:
      src: dot_env
      dest: "{{ install_folder }}/colosseum_website/.env"
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Stop celery
    command: |
      pkill --full celery
    ignore_errors: true

  - name: Start celery
    command: |
      {{ install_folder }}/pyenv/shims/python3 -m poetry run celery --app app worker --loglevel=INFO --logfile=celery.log --beat --detach
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  become: true
  become_method: su
  become_user: devops
