---
- block:
  - name: Checkout colosseum
    git:
      repo: https://github.com/h3nnn4n/colosseum_website
      dest: "{{ install_folder }}/colosseum_website"
      version: "{{ deploy_branch }}"

  - name: Ensure pip is available
    command: "{{ install_folder }}/pyenv/shims/python3 -m ensurepip"

  - name: Ensure poetry is available
    command: "{{ install_folder }}/pyenv/shims/python3 -m pip install poetry"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Install project deps with Poetry
    command: "{{ install_folder }}/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Upgrade setuptools
    command: "{{ install_folder }}/pyenv/shims/python3 -m poetry run pip install setuptools"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Setup .env file
    template:
      src: dot_env
      dest: "{{ install_folder }}/colosseum_website/.env"
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Create systemd service file for celery
    template:
      src: celery.service
      dest: /etc/systemd/system/celery.service
      owner: devops
      group: devops
      mode: '0644'
    become: true
    become_user: root

  - name: Reload systemd
    systemd:
      daemon_reload: yes
    become: true
    become_user: root

  - name: Enable and start celery service
    systemd:
      name: celery
      enabled: yes
      state: restarted
    become: true
    become_user: root

  become: true
  become_method: su
  become_user: devops
