server:
  http_listen_address: 127.0.0.1
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://{{ vault_loki_host }}/loki/api/v1/push"
    basic_auth:
      username: {{ vault_loki_user }}
      password: {{ vault_loki_password }}

scrape_configs:
- job_name: gunicorn_access_logs
  static_configs:
  - targets:
      - localhost
    labels:
      source: gunicorn
      __path__: "{{ install_folder }}/colosseum_website/access.log"
