---
- hosts: colosseum_workers
  roles:
    - role: bootstrap
      tags: ['bootstrap']

    - role: staticdev.pyenv
      pyenv_path: "{{ install_folder }}/pyenv"
      pyenv_owner: "devops"
      pyenv_global:
        - "{{ python_version }}"
      pyenv_python_versions:
        - "{{ python_version }}"
      tags: ['python']

    - role: docker
      tags: ['colosseum_worker']

    - role: colosseum_worker
      tags: ['colosseum_worker']
