---
- hosts: web_servers
  roles:
    - role: bootstrap
      tags: ['bootstrap']

    - role: staticdev.pyenv
      pyenv_path: "{{ install_folder }}/pyenv"
      pyenv_owner: "devops"
      pyenv_global:
        - 3.10.0
      pyenv_python_versions:
        - 3.10.0
      tags: ['python']

    - role: web_server
      tags: ['web_server']

    - role: nginx
      tags: ['nginx']
