---
- block:
  - name: Ensure loki group exists
    group:
      name: loki
      state: present

  - name: Ensure loki user exists
    user:
      name: loki
      shell: /bin/bash
      groups: loki

  - name: Ensure loki directory exists
    file:
      path: /mnt/metrics_volume/loki/
      state: directory
      owner: loki
      group: loki
      mode: '0755'

  - name: Download loki
    get_url:
      url: https://github.com/grafana/loki/releases/download/v2.4.2/loki-linux-amd64.zip
      dest: /mnt/metrics_volume/loki/loki-linux-amd64.zip
      owner: loki
      group: loki
      mode: '0400'  # Read-only to owner

  - name: Extract loki
    unarchive:
      src: /mnt/metrics_volume/loki/loki-linux-amd64.zip
      dest: /mnt/metrics_volume/loki/
      remote_src: yes
      owner: loki
      group: loki
      mode: '0700'

  - name: Decrypt and copy settings file file
    copy:
      src: loki_config.yml
      dest: /mnt/metrics_volume/loki/loki_config.yml
      decrypt: true
      owner: loki
      group: loki
      mode: '0400'  # Read-only to owner

  - name: Stop loki
    command: |
      pkill --full loki
    ignore_errors: true

  - name: Ensure loki is running
    shell: |
      /mnt/metrics_volume/loki/loki-linux-amd64 \
      -config.file=/mnt/metrics_volume/loki/loki_config.yml \
       >> /mnt/metrics_volume/loki/loki_stdout.log \
      2>> /mnt/metrics_volume/loki/loki_stderr.log \
      &
    args:
      executable: /bin/bash
      chdir: /mnt/metrics_volume/loki/
    become: yes
    become_method: su
    become_user: loki

  become: yes
  become_method: sudo
  become_user: root


- block:
  - name: Ensure system packages deps are present
    apt:
      pkg:
        - nginx
      state: present

  - name: Setup nginx loki site
    template:
      src: loki_site
      dest: /etc/nginx/sites-available/loki_site
      owner: root
      group: root
      mode: '0644'

  - name: Enable loki_site
    file:
      src: /etc/nginx/sites-available/loki_site
      dest: /etc/nginx/sites-enabled/loki_site
      owner: root
      group: root
      state: link

  - name: Disable default nginx site
    file:
      path: '{{ item }}'
      state: absent
    loop:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default

  - name: Ensure nginx is running
    service:
      name: nginx
      state: started

  - name: Reload nginx
    service:
      name: nginx
      state: reloaded
