---
- block:
  - name: Ensure system packages deps are present
    apt:
      pkg:
        - libpq-dev
      state: present
    become: true
    become_method: sudo
    become_user: root

  - name: Checkout colosseum_website
    git:
      repo: https://github.com/h3nnn4n/colosseum_website
      dest: /home/devops/colosseum_website
      version: production

  - name: Ensure poetry is available
    command: /home/devops/pyenv/shims/python -m pip install poetry

  - name: Install project deps with Poetry
    command: /home/devops/pyenv/shims/python3 -m poetry install
    args:
      chdir: /home/devops/colosseum_website

  - name: Decrypt and copy secret file
    copy:
      src: dot_env
      dest: /home/devops/colosseum_website/.env
      decrypt: true
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Run django migrations
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      /home/devops/pyenv/shims/python3 -m poetry run python3 manage.py migrate
    args:
      executable: /bin/bash
      chdir: /home/devops/colosseum_website

  - name: Run django collectstatic
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      /home/devops/pyenv/shims/python3 -m poetry run python3 manage.py collectstatic --no-input
    args:
      executable: /bin/bash
      chdir: /home/devops/colosseum_website

  - name: Ensure Gunicorn is not running
    shell: |
      pgrep gunicorn && pkill -f gunicorn || true
    args:
      executable: /bin/bash
      chdir: /home/devops/colosseum_website
    become: yes

  - name: Ensure Gunicorn is running
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      /home/devops/pyenv/shims/python3 -m poetry run gunicorn \
        colosseum_website.wsgi \
        --bind=unix:/home/devops/colosseum_website/gunicorn.sock \
        --keep-alive 10 \
        --access-logfile access.log \
        --log-level info \
        --log-file server.log \
        --preload \
        --timeout 30 \
        --worker-class sync \
        --workers=5 &
    args:
      executable: /bin/bash
      chdir: /home/devops/colosseum_website

  become: yes
  become_method: su
  become_user: devops
