---
- block:
  - name: Ensure system packages deps are present
    apt:
      pkg:
        - libpq-dev
      state: present
    become: true
    become_method: sudo
    become_user: root

  - name: Checkout colosseum_website
    git:
      repo: https://github.com/h3nnn4n/colosseum_website
      dest: "{{ install_folder }}/colosseum_website"
      version: production

  - name: Ensure poetry is available
    command: "{{ install_folder }}/pyenv/shims/python -m pip install poetry"

  - name: Install project deps with Poetry
    command: "{{ install_folder }}/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Setup .env file
    template:
      src: dot_env
      dest: "{{ install_folder }}/colosseum_website/.env"
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Run django migrations
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      {{ install_folder }}/pyenv/shims/python3 -m poetry run python3 manage.py migrate
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Run django collectstatic
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      {{ install_folder }}/pyenv/shims/python3 -m poetry run python3 manage.py collectstatic --no-input
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Stop gunicorn
    command: |
      pkill --full gunicorn
    ignore_errors: true

  - name: Ensure Gunicorn is running
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      {{ install_folder }}/pyenv/shims/python3 -m poetry run gunicorn \
        colosseum_website.wsgi \
        --bind=unix:{{ install_folder }}/colosseum_website/gunicorn.sock \
        --keep-alive 10 \
        --access-logfile access.log \
        --log-level info \
        --log-file server.log \
        --preload \
        --timeout 30 \
        --worker-class sync \
        --workers 5 > stuff.log &
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum_website"

  become: yes
  become_method: su
  become_user: devops
