---
- block:
  - name: Ensure system packages deps are present
    apt:
      pkg:
        - libpq-dev
      state: present
    become: true
    become_method: sudo
    become_user: root

  - name: Checkout colosseum_website
    git:
      repo: https://github.com/h3nnn4n/colosseum_website
      dest: "{{ install_folder }}/colosseum_website"
      version: "{{ deploy_branch }}"

  - name: Ensure poetry is available
    command: "{{ install_folder }}/pyenv/shims/python -m pip install poetry"

  - name: Install project deps with Poetry
    command: "{{ install_folder }}/pyenv/shims/python3 -m poetry install"
    args:
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Setup .env file
    template:
      src: dot_env
      dest: "{{ install_folder }}/colosseum_website/.env"
      owner: devops
      group: devops
      mode: '0400'  # Read only to owner

  - name: Run django migrations
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      {{ install_folder }}/pyenv/shims/python3 -m poetry run python3 manage.py migrate
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Run django collectstatic
    shell: |
      DJANGO_SETTINGS_MODULE=colosseum_website.settings.production \
      {{ install_folder }}/pyenv/shims/python3 -m poetry run python3 manage.py collectstatic --no-input
    args:
      executable: /bin/bash
      chdir: "{{ install_folder }}/colosseum_website"

  - name: Create gunicorn service
    template:
      src: gunicorn.service
      dest: /etc/systemd/system/gunicorn.service
      owner: root
      group: root
    become: yes
    become_user: root

  - name: Ensure gunicorn is enabled and restarted
    service:
      name: gunicorn.service
      enabled: yes
      state: restarted

  become: yes
  become_method: su
  become_user: devops
